config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'chatroom#index'

# Users sessions
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

# messages 
post 'message', to: 'messages#create'
mount ActionCable.server, at: '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to proceed!"
      redirect_to login_path
    end    
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "logged in successfully"
      redirect_to root_path

    else
      flash.now[:error] ="Your login credentials were not correct"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You successfully logged out"
    redirect_to root_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular comments icon"></i>
  Friends
</h2>

<div class="ui two column grid">
	<div class="twelve wide column">
		<div class="ui fluid raised card chatbox">
			<!-- Activity starts here -->
			<% if logged_in? %>
			  <div class="content" id="messages">
			    <div class="ui feed" id="message-broadcast">
			      <!-- message start -->
				    <%= render @messages %>
			    </div>
			  </div>
			  <div class="extra content">
			    <%= render 'messages/send_message' %>
			  </div>
		  <% else %>
				<div class="content">
			    <div class="ui feed">
			      <p>You need to be logged in to see the messages</p>
			    </div>
			  </div>
			<% end %>
		</div>
	</div>

<!-- Vertical menu starts here	 -->
	<div class="four wide column">
		<div class="ui fluid raised card chatbox">
		  <div class="content">
				<div class="ui vertical menu">
				  <a class="active teal item">
				    Inbox
				    <div class="ui teal left pointing label">1</div>
				  </a>
				  <a class="item">
				    Spam
				    <div class="ui label">51</div>
				  </a>
				  <a class="item">
				    Updates
				    <div class="ui label">1</div>
				  </a>
				  <div class="item">
				    <div class="ui transparent icon input">
				      <input type="text" placeholder="Search mail...">
				      <i class="search icon"></i>
				    </div>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %> 
	<div class="ui <%= name %> message">
	  <i class="close icon"></i>
	  <div class="header">
	    <%= msg %>
	  </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<a class="item">Messages</a>
<div class="right menu"> 
  <!-- <a class="item">Help</a> -->
  <div class="ui simple dropdown item">
    Account
    <i class="dropdown icon"></i>
    <div class="ui menu">
      <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item" %>
        <a class="item">Sign Up</a>
      <% end %>
      <div class="item">Other</div>
    </div>
  </div>
  <% if !logged_in? %>
  <%= link_to "Log in", login_path, class: "item" %> 
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%=favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render '/layouts/message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
	<div class="content">
		<div class="summary">
			<a><%= message.user.name %></a>: <%= message.body %>
		</div>
	</div>
</div>

app/views/messages/_send_message.html.erb
<%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
	<div class="field">
		<div class="ui fluid icon input">
			<%= f.text_field :body %>
			<%= f.button '<i class="bordered inverted red edit icon"></i>'.html_safe %>		
		</div>
	</div>
<% end %>